# Generated by Django 5.1.6 on 2026-01-18 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_image', models.ImageField(default='../placeholder_post_pic_x9ygad', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.mode
ls.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='tags.tag')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]

    # ('tags', '0001_initial'),
    #     migrations.swappable_dependency(settings.AUTH_USER_MODEL),
