# Generated by Django 5.1.6 on 2026-04-06 06:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='placeholder_post_pic_x9ygad', max_length=255, verbose_name='image'),
        ),
    ]
