# Generated by Django 5.1.6 on 2025-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='../placeholder_post_pic_x9ygad', upload_to='images/'),
        ),
    ]
