# Generated by Django 5.1.6 on 2025-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='https://res.cloudinary.com/deddv4phe/image/upload/v1711462986/placeholder_profile_pic_z5brab.png', upload_to='images/'),
        ),
    ]
