# Generated by Django 5.1.6 on 2025-12-19 06:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder_profile_pic_z5brab', max_length=255, verbose_name='image'),
        ),
    ]
